; EggDuino - EBB Protocol Emulator for Eggbot/Spherebot
; Target: Arduino Uno + CNC Shield v3

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = arduino-libraries/Servo@^1.2.2
